### ISSUE TITLE
bug：:INFO:root:customError:[GUI][ERROR] [DANSER][ERROR] runtime error: index out of range [3] with length 2

### ISSUE THREAD

**Issue by Mddzlk686** [spaceskynet/danser-gui#3]
2023-06-24 12:14:26,845:INFO:root:read:[GUI][CONFIG] GUI Config is read from: E:\dancer\settings.toml
2023-06-24 12:14:26,845:WARNING:root:initDanserConfig:[GUI][CONFIG] Danser Config can't be found in: C:\Users\Administrator\Desktop\dancer\settings\default.json
2023-06-24 12:14:27,048:INFO:root:__init__:[GUI] Current settings is updated to: {'General': {'OsuRootDir': 'C:\\Users\\Administrator\\Desktop\\osu', 'OsuSongsDir': 'C:\\Users\\Administrator\\Desktop\\osu\\Songs', 'OsuSkinsDir': 'C:\\Users\\Administrator\\Desktop\\osu\\Skins', 'DanserRootDir': 'C:\\Users\\Administrator\\Desktop\\dancer', 'DanserMode': 'replay', 'IsRecord': True, 'SongsDBMode': 'osu!', 'OsuApi': '', 'Language': 'zh-CN', 'WindowWidth': 720, 'WindowHeight': 405}, 'Graphics': {'Fullscreen': True, 'Width': 1440, 'Height': 900, 'VSync': False, 'MSAA': 0, 'FPSCap': 999, 'ShowFPS': True}, 'Knockout': {'Mode': 2, 'GraceEndTime': -10.0, 'ExcludeMods': '', 'HideMods': '', 'MaxPlayers': 50, 'BubbleMinimumCombo': 200, 'RevivePlayersAtEnd': False, 'LiveSort': True, 'SortBy': 'Score', 'HideOverlayOnBreaks': False, 'MinCursorSize': 0.5, 'MaxCursorSize': 2.0, 'AddDanser': True, 'DanserName': 'danser-gui', 'DateFormat': 0}, 'Recording': {'FrameWidth': 1440, 'FrameHeight': 900, 'FPS': 120, 'Encoder': 'cpu', 'MotionBlur': False, 'OutputPath': 'C:\\Users\\Administrator\\Desktop\\dancer\\Videos', 'OutputName': '{Player} - {Artist}[{Creator}] - {MapTitle}[{Difficulty}].mp4', 'LocalAudioOffset': 0, 'EncoderConfig': {'VideoCodec': 'libx264', 'EncoderOptions': '-crf 21 -g 450', 'Preset': 'faster', 'AudioCodec': 'aac', 'AudioOptions': '-b:a 192k'}}, 'Audio': {'GlobalVolume': 100, 'MusicVolume': 100, 'HitSoundVolume': 100}, 'Input': {'LeftKey': 'Z', 'RightKey': 'X', 'RestartKey': '`', 'SmokeKey': 'C', 'MouseButtonsDisabled': False}, 'Gameplay': {'PlayUsername': 'Mddzlh', 'HitErrorMeter': {'Show': True, 'ShowUnstableRate': True}, 'Score': {'Show': True}, 'HpBar': {'Show': True}, 'ComboCounter': {'Show': True}, 'PPCounter': {'Show': True, 'UseLazerPP': False}, 'StrainGraph': {'Show': True}, 'KeyOverlay': {'Show': True}, 'ScoreBoard': {'Show': True, 'HideOthers': True, 'ShowAvatars': False, 'ModsOnly': False}, 'HitCounter': {'Show': True}, 'AimErrorMeter': {'Show': True}, 'Boundaries': {'Show': True}, 'Mods': {'Show': True, 'HideInReplays': False, 'FoldInReplays': False}, 'ResultsScreen': {'Show': True, 'Time': 5, 'UseLocalTimeZone': True}}, 'Skin': {'CurrentSkin': 'default', 'UseSkinColors': True, 'UseBeatmapColors': False, 'UseSkinCursor': True, 'UseSkinHitsounds': True}, 'Cursor': {'ScaleToCS': True, 'CursorRainbow': False, 'CursorTrailGlow': False, 'CursorSize': 0.68, 'CursorRipples': False, 'ForceLongTrail': False, 'LongTrailDensity': 0, 'LongTrailLength': 0}, 'Objects': {'DrawFollowPoints': True, 'DrawComboNumbers': True, 'ScaleToTheBeat': False, 'SliderMerge': False, 'Rainbow': False, 'FlashToTheBeat': False, 'UseHitCircleColor': True, 'SliderSnakingIn': True, 'SliderSnakingOut': True}, 'Playfield': {'SeizureWarning': False, 'LoadStoryboard': True, 'LoadVideo': True, 'IntroBGDim': 0, 'InGameBGDim': 80, 'BreakBGDim': 50, 'BGParallax': False, 'ShowDanserLogo': False, 'QuickStart': True, 'SkipIntro': True}}
2023-06-24 12:14:27,063:INFO:root:setLanguage:[GUI] Language changed to 中文（简体）, *.qm file in: E:\dancer\langs\zh-CN\lang.qm
2023-06-24 12:14:27,079:INFO:root:customWarning:[GUI][WARNING] 近期没有回放文件，请自行选择回放文件！
2023-06-24 12:14:31,201:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:14:31,217:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!
2023-06-24 12:14:47,892:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:14:47,892:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!
2023-06-24 12:14:47,892:INFO:root:read:[DANSER][CONFIG] Danser Config is read from: E:\dancer\settings\default.json
2023-06-24 12:14:56,764:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:14:56,764:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!
2023-06-24 12:14:56,768:INFO:root:write:[DANSER][CONFIG] Danser Config is written to: E:\dancer\settings\default.json
2023-06-24 12:14:56,768:INFO:root:syncDanserConfigWithGuiConfig:[GUI] sync Danser Config With GuiConfig Done!
2023-06-24 12:14:56,769:INFO:root:songsDBUpdateEventStarted:[GUI] songsDBUpdateEvent Started
2023-06-24 12:14:56,769:TRACE:utils.osudbparser.osu_to_sqlite:create_db:CALL *('C:\\Program Files (x86)\\osu\\osu!.db', 'E:\\dancer\\osu!.sqlite3.db') **{}
2023-06-24 12:14:56,874:TRACE:utils.osudbparser.osu_to_sqlite:create_db:RETURN None
2023-06-24 12:14:56,874:INFO:root:run:[GUI][SongsDBUpdateThread][osu!] Finshed!
2023-06-24 12:14:57,061:INFO:root:<lambda>:[DANSER][STDERR] 2023/06/24 12:14:57 danser-go version: 0.6.9

2023-06-24 12:14:57,174:INFO:root:<lambda>:[DANSER][STDOUT] 2023/06/24 12:14:57 Checking GitHub for a new version of danser...

2023-06-24 12:14:57,865:INFO:root:<lambda>:[DANSER][STDOUT] 2023/06/24 12:14:57 You're using an older version of danser.
2023/06/24 12:14:57 You can download a newer version here: https://github.com/Wieku/danser-go/releases/tag/0.8.4

2023-06-24 12:15:00,049:INFO:root:<lambda>:[DANSER][STDOUT] 2023/06/24 12:14:59 SettingsManager: Loading "E:\dancer\settings\default.json"
2023/06/24 12:14:59 SettingsManager: Saving current settings to "E:\dancer\settings\default.json"
2023/06/24 12:14:59 DatabaseManager: Initializing database...
2023/06/24 12:14:59 DatabaseManager: Database schema version: 20210423
2023/06/24 12:14:59 DatabaseManager: Database data version: 20210423
2023/06/24 12:14:59 DatabaseManager: Scanning "C:\Program Files (x86)\osu\Songs" for .osu files...
2023/06/24 12:14:59 DatabaseManager: Scan complete. Found 622 files.
2023/06/24 12:14:59 DatabaseManager: Comparing files with database...
2023/06/24 12:14:59 DatabaseManager: Compare complete.
2023/06/24 12:14:59 DatabaseManager: Removing leftover maps from database...
2023/06/24 12:14:59 DatabaseManager: Removal complete.
2023/06/24 12:14:59 DatabaseManager: Starting import of 622 maps. It may take up to several minutes...
2023/06/24 12:15:00 DatabaseManager: Failed to import: 1151309 Stonebank - Be Alright (feat EMEL) (Cut Ver)\Stonebank - Be Alright (feat. EMEL) (Cut Ver.) (Nhawak) [Hard].osu

2023-06-24 12:15:00,090:INFO:root:<lambda>:[DANSER][STDERR] panic: runtime error: index out of range [3] with length 2

goroutine 38 [running]:
github.com/wieku/danser-go/app/beatmap.ParseBeatMap(0xc0001addc0)
	github.com/wieku/danser-go/app/beatmap/parser.go:194 +0x852
github.com/wieku/danser-go/app/beatmap.ParseBeatMapFile(0xc000094050)
	github.com/wieku/danser-go/app/beatmap/parser.go:233 +0xc5

2023-06-24 12:15:00,105:INFO:root:<lambda>:[DANSER][STDERR] github.com/wieku/danser-go/app/database.importMaps.func2({{0xc000088161?, 0x0?}, {0xc0000880f0?, 0x0?}})
	github.com/wieku/danser-go/app/database/manager.go:317 +0x1d2
github.com/wieku/danser-go/framework/util.Balance[...].func1()
	github.com/wieku/danser-go/framework/util/balancer.go:22 +0xb7
created by github.com/wieku/danser-go/framework/util.Balance[...]
	github.com/wieku/danser-go/framework/util/balancer.go:18 +0x119

2023-06-24 12:15:00,152:INFO:root:<lambda>:[GUI][SongsDBUpdateThread][danser] Finshed!
2023-06-24 12:15:00,152:INFO:root:songsDBUpdateEventFinished:[GUI] songsDBUpdateEvent Finished
2023-06-24 12:15:00,152:INFO:root:customInfo:[GUI][INFO] 谱面数据库成功更新！
2023-06-24 12:15:02,581:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:15:02,581:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!
2023-06-24 12:15:03,087:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:15:03,087:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!
2023-06-24 12:15:03,578:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:15:03,578:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!
2023-06-24 12:15:06,592:INFO:root:osrSelectButtonClicked:[GUI] Chosen osr file: C:/Program Files (x86)/osu/Replays/Mddzlh - Hige Driver - Miracle Sugite Yabai (feat. shully) [Easy] (2023-06-18) Osu.osr
2023-06-24 12:15:06,623:INFO:root:setBeatmap:[GUI] Chosen osu file: C:\Program Files (x86)\osu\Songs\682290 Hige Driver - Miracle Sugite Yabai (feat shully)\Hige Driver - Miracle Sugite Yabai (feat. shully) (Milan-) [Easy].osu
2023-06-24 12:15:07,495:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:15:07,495:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!
2023-06-24 12:15:07,511:INFO:root:write:[DANSER][CONFIG] Danser Config is written to: E:\dancer\settings\default.json
2023-06-24 12:15:07,511:INFO:root:syncDanserConfigWithGuiConfig:[GUI] sync Danser Config With GuiConfig Done!
2023-06-24 12:15:07,526:INFO:root:generateArgumentsByGuiConfig:[GUI] Output file name: Mddzlh - Hige Driver[Milan-] - Miracle Sugite Yabai (feat. shully)[Easy]
2023-06-24 12:15:07,526:INFO:root:generateArgumentsByGuiConfig:[GUI] Danser execute arguments: ['-noupdatecheck', '-nodbcheck', '-quickstart', '-md5=6a789dcc6aefaf75f0b971eaa0b58ee8', '-out', 'Mddzlh - Hige Driver[Milan-] - Miracle Sugite Yabai (feat. shully)[Easy]', '-replay', 'C:\\Program Files (x86)\\osu\\Replays\\Mddzlh - Hige Driver - Miracle Sugite Yabai (feat. shully) [Easy] (2023-06-18) Osu.osr']
2023-06-24 12:15:07,589:INFO:root:startDanserByArgumentsEventStarted:[GUI] startDanserByArgumentsEvent Started
2023-06-24 12:15:07,682:INFO:root:<lambda>:[DANSER][STDERR] 
2023-06-24 12:15:07,728:INFO:root:<lambda>:[DANSER][STDOUT] 2023/06/24 12:15:07 SettingsManager: Loading "E:\dancer\settings\default.json"
2023/06/24 12:15:07 SettingsManager: Saving current settings to "E:\dancer\settings\default.json"
2023/06/24 12:15:07 DatabaseManager: Initializing database...
2023/06/24 12:15:07 DatabaseManager: Database schema version: 20210423
2023/06/24 12:15:07 DatabaseManager: Database data version: 20210423
2023/06/24 12:15:07 DatabaseManager: Scanning "C:\Program Files (x86)\osu\Songs" for .osu files...
2023/06/24 12:15:07 DatabaseManager: '-nodbcheck' is active so only new directories will be imported.

2023-06-24 12:15:07,740:INFO:root:<lambda>:[DANSER][STDOUT] 2023/06/24 12:15:07 DatabaseManager: Scan complete. Found 622 files.
2023/06/24 12:15:07 DatabaseManager: Comparing files with database...

2023-06-24 12:15:07,777:INFO:root:<lambda>:[DANSER][STDOUT] 2023/06/24 12:15:07 DatabaseManager: Compare complete.
2023/06/24 12:15:07 DatabaseManager: Starting import of 622 maps. It may take up to several minutes...

2023-06-24 12:15:07,879:INFO:root:<lambda>:[DANSER][STDOUT] 2023/06/24 12:15:07 DatabaseManager: Failed to import: 1151309 Stonebank - Be Alright (feat EMEL) (Cut Ver)\Stonebank - Be Alright (feat. EMEL) (Cut Ver.) (Nhawak) [Hard].osu

2023-06-24 12:15:07,931:INFO:root:<lambda>:[DANSER][STDERR] 
2023-06-24 12:15:07,962:INFO:root:<lambda>:[GUI][DanserExecByArgsThread] Finshed!
2023-06-24 12:15:07,962:INFO:root:startDanserByArgumentsEventFinished:[GUI] startDanserByArgumentsEvent Finished
2023-06-24 12:15:07,978:INFO:root:customError:[GUI][ERROR] [DANSER][ERROR] runtime error: index out of range [3] with length 2
2023-06-24 12:20:23,712:INFO:root:write:[GUI][CONFIG] GUI Config is written to: E:\dancer\settings.toml
2023-06-24 12:20:23,713:INFO:root:syncGuiConfigWithMainWindow:[GUI] sync GuiConfig With MainWindow Done!

**Comment by ghost** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
